Chore/resolve workflow conflict (#15)
* Update workflow yml in main branch

caching + artifact upload + flaky test debug logging

* code quality checks added (#12)

* Update liveweather-ci.yml (#9)

caching + artifact upload + flaky test debug logging

* Update liveweather-ci.yml

Code quality job added

* Update liveweather-ci.yml

python installation error changes

* Update liveweather-ci.yml

semgr typo error corrected in code quality check step

* Update liveweather-ci.yml

* Update liveweather-ci.yml

* Update liveweather-ci.yml

* swift format changes

* swift format changes and yml files added for swiftformat, swiftlint and swift version

* ForecastResponseDTO.swift: renamed temp_c property to Swift style

* swift lint issues done and UItests excluded from linting

* swift formatting issues resolved:
Repositories.swift:9:1: error: (wrapMultilineStatementBraces) Wrap the opening brace of multiline statements.

---------

Co-authored-by: prashantgtm1001 <69428201+prashantgtm1001@users.noreply.github.com>

---------

Co-authored-by: prashantgtm1001 <69428201+prashantgtm1001@users.noreply.github.com>