Merge development into main (#19)
* Update liveweather-ci.yml (#9)

caching + artifact upload + flaky test debug logging

* Update liveweather-ci.yml

Code quality job added

* Update liveweather-ci.yml

python installation error changes

* Update liveweather-ci.yml

semgr typo error corrected in code quality check step

* Update liveweather-ci.yml

* Update liveweather-ci.yml

* Update liveweather-ci.yml

* swift format changes

* swift format changes and yml files added for swiftformat, swiftlint and swift version

* ForecastResponseDTO.swift: renamed temp_c property to Swift style

* swift lint issues done and UItests excluded from linting

* swift formatting issues resolved:
Repositories.swift:9:1: error: (wrapMultilineStatementBraces) Wrap the opening brace of multiline statements.

* Sonar Qube properties file added (#13)

* Sonar Qube properties file added
Sonar qube job added in the Github Action workflow file

* Update liveweather-ci.yml

* Update liveweather-ci.yml

SHA added for Sonar Qube

* sonar properties file updated - fixtures are removed from the tests source

* Chore/resolve workflow conflict (#15)

* Update workflow yml in main branch

caching + artifact upload + flaky test debug logging

* code quality checks added (#12)

* Update liveweather-ci.yml (#9)

caching + artifact upload + flaky test debug logging

* Update liveweather-ci.yml

Code quality job added

* Update liveweather-ci.yml

python installation error changes

* Update liveweather-ci.yml

semgr typo error corrected in code quality check step

* Update liveweather-ci.yml

* Update liveweather-ci.yml

* Update liveweather-ci.yml

* swift format changes

* swift format changes and yml files added for swiftformat, swiftlint and swift version

* ForecastResponseDTO.swift: renamed temp_c property to Swift style

* swift lint issues done and UItests excluded from linting

* swift formatting issues resolved:
Repositories.swift:9:1: error: (wrapMultilineStatementBraces) Wrap the opening brace of multiline statements.

---------

Co-authored-by: prashantgtm1001 <69428201+prashantgtm1001@users.noreply.github.com>

---------

Co-authored-by: prashantgtm1001 <69428201+prashantgtm1001@users.noreply.github.com>

* Chore/sync main into development (#17)

* Update workflow yml in main branch

caching + artifact upload + flaky test debug logging

* code quality checks added (#12)

* Update liveweather-ci.yml (#9)

caching + artifact upload + flaky test debug logging

* Update liveweather-ci.yml

Code quality job added

* Update liveweather-ci.yml

python installation error changes

* Update liveweather-ci.yml

semgr typo error corrected in code quality check step

* Update liveweather-ci.yml

* Update liveweather-ci.yml

* Update liveweather-ci.yml

* swift format changes

* swift format changes and yml files added for swiftformat, swiftlint and swift version

* ForecastResponseDTO.swift: renamed temp_c property to Swift style

* swift lint issues done and UItests excluded from linting

* swift formatting issues resolved:
Repositories.swift:9:1: error: (wrapMultilineStatementBraces) Wrap the opening brace of multiline statements.

---------

Co-authored-by: prashantgtm1001 <69428201+prashantgtm1001@users.noreply.github.com>

---------

Co-authored-by: prashantgtm1001 <69428201+prashantgtm1001@users.noreply.github.com>

---------

Co-authored-by: prashantgtm1001 <69428201+prashantgtm1001@users.noreply.github.com>